book_repo: pivotal-cf/docs-book-wavefront-nozzle
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: "edge"

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-wavefront-nozzle
    at_path: docs-content
    ref: "master"
  directory: wavefront-nozzle/3-n
  subnav_template: wavefront-nozzle_subnav.erb

  product_info:
    use_local_header: true
    latest_stable_version: 3.0.0
    changelog_href: https://docs-pcf-staging.sc2-04-pcf1-apps.oc.vmware.com/wavefront-nozzle/3-n/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: VMware Tanzu Observability by Wavefront Nozzle
    search_placeholder: VMware Tanzu Observability by Wavefront Nozzle 3.1
    url_prefix: /wavefront-nozzle/3-n
    local_product_version: "3.1"
    local_header_links: []
    local_header_version_list:
